export const effectsNames: Array<string> = [
  "Weakness to Frost",
  "Fortify Sneak",
  "Weakness to Poison",
  "Fortify Restoration",
  "Damage Stamina",
  "Fortify Conjuration",
  "Damage Magicka Regen",
  "Fortify Enchanting",
  "Restore Stamina",
  "Fortify Health",
  "Fortify One-handed",
  "Ravage Stamina",
  "Regenerate Stamina",
  "Weakness to Shock",
  "Resist Poison",
  "Fortify Light Armor",
  "Fortify Destruction",
  "Weakness to Fire",
  "Fortify Block",
  "Resist Magic",
  "Frenzy",
  "Restore Health",
  "Fortify Smithing",
  "Resist Shock",
  "Fortify Pickpocket",
  "Fear",
  "Resist Fire",
  "Restore Magicka",
  "Paralysis",
  "Fortify Magicka",
  "Fortify Barter",
  "Lingering Damage Stamina",
  "Damage Magicka",
  "Fortify Marksman",
  "Cure Disease",
  "Fortify Stamina",
  "Invisibility",
  "Waterbreathing",
  "Damage Stamina Regen",
  "Fortify Carry Weight",
  "Weakness to Magic",
  "Damage Health",
  "Ravage Health",
  "Slow",
  "Fortify Illusion",
  "Fortify Two-handed",
  "Regenerate Magicka",
  "Fortify Lockpicking",
  "Resist Frost",
  "Ravage Magicka",
  "Regenerate Health",
  "Fortify Alteration",
  "Lingering Damage Magicka",
  "Fortify Heavy Armor",
  "Lingering Damage Health"
]

export const ingredientNames: Array<string> = [
  "Abecean Longfin",
  "Ancestor Moth Wing",
  "Bear Claws",
  "Bee",
  "Beehive Husk",
  "Bleeding Crown",
  "Blisterwort",
  "Blue Butterfly Wing",
  "Blue Dartwing",
  "Blue Mountain Flower",
  "Bone Meal",
  "Briar Heart",
  "Butterfly Wing",
  "Canis Root",
  "Charred Skeever Hide",
  "Chaurus Eggs",
  "Chaurus Hunter Antennae",
  "Chicken's Egg",
  "Creep Cluster",
  "Crimson Nirnroot",
  "Cyrodilic Spadetail",
  "Daedra Heart",
  "Deathbell",
  "Dragon's Tongue",
  "Dwarven Oil",
  "Ectoplasm",
  "Elves Ear",
  "Eye of Sabre Cat",
  "Falmer Ear",
  "Fire Salts",
  "Fly Amanita",
  "Frost Mirriam",
  "Frost Salts",
  "Garlic",
  "Giant Lichen",
  "Giant's Toe",
  "Gleamblossom",
  "Glow Dust",
  "Glowing Mushroom",
  "Grass Pod",
  "Hagraven Claw",
  "Hagraven Feathers",
  "Hanging Moss",
  "Hawk Beak",
  "Hawk Feathers",
  "Hawk's Egg",
  "Histcarp",
  "Honeycomb",
  "Human Flesh",
  "Human Heart",
  "Ice Wraith Teeth",
  "Imp Stool",
  "Jazbay Grapes",
  "Juniper Berries",
  "Large Antlers",
  "Lavender",
  "Luna Moth Wing",
  "Moon Sugar",
  "Mora Tapinella",
  "Mudcrab Chitin",
  "Namira's Rot",
  "Nightshade",
  "Nirnroot",
  "Nordic Barnacle",
  "Orange Dartwing",
  "Pearl",
  "Pine Thrush Egg",
  "Poison Bloom",
  "Powdered Mammoth Tusk",
  "Purple Mountain Flower",
  "Red Mountain Flower",
  "River Betty",
  "Rock Warbler Egg",
  "Sabre Cat Tooth",
  "Salmon Roe",
  "Salt Pile",
  "Scaly Pholiota",
  "Silverside Perch",
  "Skeever Tail",
  "Slaughterfish Egg",
  "Slaughterfish Scales",
  "Small Antlers",
  "Small Pearl",
  "Snowberries",
  "Spider Egg",
  "Spriggan Sap",
  "Swamp Fungal Pod",
  "Taproot",
  "Thistle Branch",
  "Torchbug Thorax",
  "Troll Fat",
  "Tundra Cotton",
  "Vampire Dust",
  "Void Salts",
  "Wheat",
  "White Cap",
  "Wisp Wrappings",
  "Yellow Mountain Flower",
  "Ash Creep Cluster",
  "Ash Hopper Jelly",
  "Ashen Grass Pod",
  "Boar Tusk",
  "Burnt Spriggan Wood",
  "Emperor Parasol Moss",
  "Felsaad Tern Feathers",
  "Netch Jelly",
  "Scathecraw",
  "Spawn Ash",
  "Trama Root"
]

export const potionNames: Array<string> = [
  "Potion of Alteration",
  "Draught of Alteration",
  "Philter of Alteration",
  "Elixir of Alteration",
  "Potion of Haggling",
  "Draught of Haggling",
  "Philter of Haggling",
  "Elixir of Haggling",
  "Potion of the Defender",
  "Draught of the Defender",
  "Philter of the Defender",
  "Elixir of the Defender",
  "Phial of Stunning",
  "Elixir of Godly Powers",
  "Philter of Immortality",
  "Brew of Lies",
  "Philter of Lies",
  "Philter of Reversed Growth",
  "Flask of the Seer",
  "Flask of Serenity",
  "Draught of Souls",
  "Philter of Illusions",
  "Potion of Haste",
  "Elixir of Mindbending",
  "Tonic of Efficiency",
  "Elixir of Wealth",
  "Philter of Mageblood",
  "Draught of Focus",
  "Tonic of Dawn",
  "Phial of Honesty",
  "Vial of Eternal Rage",
  "Tonic of Victory",
];


